import { describe, it, expect, vi } from "vitest";
import { mkdtemp, mkdir, writeFile, symlink, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createTrustedPlugin, type TrustedPluginDeps } from "./trusted-plugin.js";
import { createTrustedFiles } from "./trusted-plugin-files.js";
async function fixture(){const root=await mkdtemp(join(tmpdir(),"pi-trusted-"));const calls:{method:string;params:any}[]=[];let listener:((m:string,p:unknown)=>void)|undefined;
const h={call:async(method:string,params:any)=>{calls.push({method,params});if(method==="scheduled.pluginSessionOwnership")return {state:"owned"};if(method==="session.configure")return {session:{id:params.id,permissionMode:params.permissionMode}};return {};},onNotification:(l:any)=>{listener=l;return ()=>{listener=undefined;};}};const deps={getHost:()=>h,getSidecar:()=>null,runtime:{onTurnEnded:()=>()=>{},activeTurnId:()=>"turn-1"},agentHost:{},log:()=>{}} as unknown as TrustedPluginDeps;
const plugin=createTrustedPlugin({manifest:{id:"local.pi-bot",permissions:["desktop.control","agent.tool.register"]},dataDir:join(root,"state"),workspaceRoots:[root]},deps);
return {root,calls,plugin,notify:(m:string,p:unknown)=>listener?.(m,p),close:async()=>{plugin.stop();await rm(root,{recursive:true,force:true});}};}
describe("headless first-party broker",()=>{
it("does not accept payload authority for a mutation",async()=>{const f=await fixture();try{await expect(f.plugin.api.desktop.invoke({operation:"agent/abort",args:[{sessionId:"s1",turnId:"turn-1",panelAuthorized:true}]})).rejects.toThrow("principal");expect(f.calls).toEqual([]);}finally{await f.close();}});
it("requires exact one-time user consent before configure reaches Host",async()=>{const f=await fixture();try{const principal={userId:"owner" as const,deviceId:"phone"};const configured=f.plugin.runAsWebUser(principal,()=>f.plugin.api.desktop.invoke({operation:"session/configure",confirm:true,args:["s1",{mode:"agent",permissionMode:"ask"}]}));await vi.waitFor(()=>expect(f.plugin.pendingConsents()).toHaveLength(1));const approval=f.plugin.pendingConsents()[0]!;
expect(()=>f.plugin.respondConsent(principal,approval.id,"wrong","approve")).toThrow("changed");expect(f.calls.some(c=>c.method==="session.configure")).toBe(false);f.plugin.respondConsent(principal,approval.id,approval.hash,"approve");await configured;expect(f.calls.find(c=>c.method==="session.configure")?.params.permissionMode).toBe("ask");expect(()=>f.plugin.respondConsent(principal,approval.id,approval.hash,"approve")).toThrow("unavailable");}finally{await f.close();}});
it("registers a real runtime tool catalog and denies mismatched turn dispatch",async()=>{const f=await fixture();try{const execute=vi.fn(async()=>"result");await f.plugin.api.agent.registerTool({name:"bot_workbench",description:"Workbench",schema:{type:"object"},execute});expect(f.plugin.toolCatalog()[0]).toMatchObject({name:"plugin_local_pi_bot_bot_workbench",parameters:{type:"object"}});f.notify("plugins.execute",{executionId:"e1",toolName:"plugin_local_pi_bot_bot_workbench",sessionId:"s1",turnId:"old",args:{},mode:"agent"});await vi.waitFor(()=>expect(f.calls.some(c=>c.method==="plugins.resolveExecution")).toBe(true));expect(execute).not.toHaveBeenCalled();expect(f.calls.find(c=>c.method==="plugins.resolveExecution")?.params.ok).toBe(false);}finally{await f.close();}});
it("executes only Host-attributed live tool calls and returns the actual result",async()=>{const f=await fixture();try{await f.plugin.api.agent.registerTool({name:"bot_workbench",description:"Workbench",schema:{},execute:async()=>"real callback"});f.notify("plugins.execute",{executionId:"e2",toolName:"plugin_local_pi_bot_bot_workbench",sessionId:"s1",turnId:"turn-1",args:{},mode:"agent"});await vi.waitFor(()=>expect(f.calls.find(c=>c.method==="plugins.resolveExecution")?.params).toMatchObject({ok:true,content:"real callback"}));}finally{await f.close();}});
});
describe("registered plugin file boundary",()=>{it("refuses traversal, absolute paths and symlink escapes",async()=>{const root=await mkdtemp(join(tmpdir(),"pi-files-"));try{await mkdir(join(root,"project"));await writeFile(join(root,"secret"),"private");const files=createTrustedFiles([join(root,"project")],async()=>join(root,"project"));await expect(files.api.readText("../secret")).rejects.toThrow();await expect(files.api.readText(join(root,"secret"))).rejects.toThrow();await mkdir(join(root,"outside"));await writeFile(join(root,"outside","secret"),"private");await symlink(join(root,"outside"),join(root,"project","link"),process.platform==="win32"?"junction":"dir");await expect(files.api.readText("link/secret")).rejects.toThrow("Symlink");await files.api.writeText("report.md","verified");expect(await files.api.readText("report.md")).toBe("verified");}finally{await rm(root,{recursive:true,force:true});}});});
